# Dependabot configuration for automated dependency updates
# Updates dependencies daily for all package managers used in the project

version: 2
updates:
  # Root npm dependencies (workspaces, e2e tests)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "root"
      - "automerge"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "backend"
      - "automerge"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "frontend"
      - "automerge"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  # VSCode Extension npm dependencies
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "vscode-extension"
      - "automerge"
    commit-message:
      prefix: "chore(vscode-extension)"
      include: "scope"

  # Python worker pip dependencies
  - package-ecosystem: "pip"
    directory: "/python-worker"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python-worker"
      - "automerge"
    commit-message:
      prefix: "chore(python-worker)"
      include: "scope"

  # Root Python dependencies (if any)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "automerge"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
      - "automerge"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
