changelog:
  categories:
    - title: 💥 Breaking changes
      labels: [breaking]
    - title: ✨ Features
      labels: [feature, enhancement]
    - title: 🐛 Fixes
      labels: [bug, fix]
    - title: 🧰 Maintenance
      labels: [chore, deps]
    - title: 🔒 Security
      labels: [security]
