version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flowstate-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flowstate_ai
      POSTGRES_USER: flowstate
      POSTGRES_PASSWORD: flowstate_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flowstate-network
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  flowstate-network:
    driver: bridge