global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'flowstate-ai'
    environment: '${ENVIRONMENT}'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend Node.js application
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend'

  # Frontend nginx
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'frontend'

  # Python worker
  - job_name: 'python-worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python-worker:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'python-worker'

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

