apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: flowstate
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/OWNER/REPO-backend:TAG
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
