name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-approve:
    runs-on: ubuntu-latest
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve patch and minor updates
        # Auto-approve patch and minor version updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patch and minor updates
        # Enable auto-merge for patch and minor updates
        # GitHub will merge automatically once all required status checks pass
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major version updates
        # Leave a comment for major version updates requiring manual review
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment "$PR_URL" --body "🔔 **Major version update detected**

          This PR updates a dependency to a new major version, which may include breaking changes.
          
          **Package:** ${{ steps.metadata.outputs.dependency-names }}
          **Update Type:** Major version update
          
          Please review the changelog and test thoroughly before merging manually.
          
          CI must pass before this can be merged."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on auto-merge enabled
        # Comment when auto-merge is enabled for patch/minor updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr comment "$PR_URL" --body "✅ **Auto-merge enabled**

          This Dependabot PR will be automatically merged after all CI checks pass.
          
          **Package:** ${{ steps.metadata.outputs.dependency-names }}
          **Update Type:** ${{ steps.metadata.outputs.update-type }}
          
          The PR has been approved and will merge automatically when all required checks succeed."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
