name: Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ctx:
          - .
          - ./backend
          - ./frontend
          - ./python-worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive sanitized image name
        id: sanitize
        run: |
          ctx="${{ matrix.ctx }}"
          sanitized="${ctx#./}"
          if [ -z "$sanitized" ] || [ "$sanitized" = "." ]; then
            sanitized="root"
          fi
          sanitized="${sanitized//\//-}"
          echo "name=$sanitized" >> "$GITHUB_OUTPUT"

      - name: Build & push ${{ matrix.ctx }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.ctx }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.sanitize.outputs.name }}

      - name: Trivy image scan ${{ matrix.ctx }}
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository }}:${{ steps.sanitize.outputs.name }}
          format: sarif
          output: trivy-${{ steps.sanitize.outputs.name }}.sarif

      - name: Upload Trivy scan results ${{ matrix.ctx }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ steps.sanitize.outputs.name }}.sarif
