name: gitleaks
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '17 3 * * 2'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose
