name: linkcheck
on:
  schedule: [ { cron: '23 4 * * 1' } ]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose docs/**/*.md
