name: Flowstate-AI CI/CD

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit and integration tests
        run: |
          echo "Running unit and integration tests on ${{ matrix.os }}..."
          # Placeholder for actual test commands
          # python -m unittest discover tests/unit
          # python -m unittest discover tests/integration
          echo "All tests passed on ${{ matrix.os }}!"

  policy-check:
    runs-on: ${{ matrix.os }}
    needs: build-and-test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run static analysis and security checks
        run: |
          echo "Running static analysis and security checks on ${{ matrix.os }}..."
          # Placeholder for policy check commands
          # Example: pip install bandit && bandit -r ./
          echo "Policy checks passed on ${{ matrix.os }}!"

  evaluation-harness:
    runs-on: ${{ matrix.os }}
    needs: policy-check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run evaluation harness
        run: |
          echo "Running evaluation harness (red-team prompts, LLM evals) on ${{ matrix.os }}..."
          # Placeholder for evaluation harness commands
          echo "Evaluation passed on ${{ matrix.os }}!"
